Homework04
NataliiaGD/Hordiienko-12.12.22 pull request #1
Opened 2022-12-25 19:55 UTC by NataliiaGD

2023-01-04 17:11 UTC, IIUPAMET requested changes

2023-01-04 17:11 UTC, mykolaFilimonov commented on src/Hometask4/Magnitude.java
> +    public static String Math (int a,int b){
назви методів з маленької літери

2023-01-04 17:11 UTC, mykolaFilimonov commented on src/Hometask4/Magnitude.java
> +    public static String Math (int a,int b){
також даємо більш зрозумілі назви параметрам та методу

2023-01-04 17:11 UTC, mykolaFilimonov commented on src/Hometask4/Magnitude.java
> +        }
використовувати конструкцію else if

2023-01-04 17:11 UTC, mykolaFilimonov commented on src/Hometask4/Magnitude.java
> +        return str;
чи потрапемо ми сюди колись?

2023-01-07 21:20 UTC, NataliiaGD commented on src/Hometask4/Magnitude.java
> +    public static String Math (int a,int b){
Назву методу змінила

2023-01-07 21:21 UTC, NataliiaGD commented on src/Hometask4/Magnitude.java
> +        }
Оновила

2023-01-07 21:22 UTC, NataliiaGD commented on src/Hometask4/Magnitude.java
> +        return str;
Потрапимо, якщо матимемо однакові ввідні дані (наприклад -9, -9)

2023-01-10 19:43 UTC, merged