Homework05
NataliiaGD/Hordiienko-12.12.22 pull request #2
Opened 2023-01-04 11:53 UTC by NataliiaGD

2023-01-04 17:24 UTC, IIUPAMET requested changes

2023-01-04 17:24 UTC, IIUPAMET commented on src/Hometask5/Task3.java
> +            intArray[i] = randomNumbers();
чого генерація і підрахунок разом, хотілосяб що це було окремо

2023-01-04 17:24 UTC, IIUPAMET commented on src/Hometask5/Task2.java
> +        for(int i = 0;i < intArray.length; i++){
чого цикл не винести окремо, і також генерацію окремо

2023-01-07 21:45 UTC, NataliiaGD commented on src/Hometask5/Task3.java
> +            intArray[i] = randomNumbers();
Винесла в окремі методи

2023-01-07 21:45 UTC, NataliiaGD commented on src/Hometask5/Task2.java
> +        for(int i = 0;i < intArray.length; i++){
Також винесла в окремі методи

2023-01-10 19:12 UTC, IIUPAMET approved these changes
загалом все добре просто розділіть гілки або зробіть мерджи попорядку не забувши після першого мерджу синхронізувати гілку з мастером / менйном

2023-01-10 19:12 UTC, IIUPAMET commented on src/Hometask4/CheckOddEven.java
> +public class CheckOddEven {
зайва домашня робота в коміті бажано прибрати або розділити
розглядали окремо в кінці заняття тому бажано виправити і не забувати в майбутньому створювати нові гілки від гілки мейн перемістившись на неї на пряму

2023-01-10 19:12 UTC, IIUPAMET commented on src/Hometask5/Task2.java
> +        } return intArray;
реторн краще окремим рядком

2023-01-10 19:12 UTC, IIUPAMET commented on src/Hometask5/Task1.java
> +    public static double calculateSin(double x){
зайва функція так як у нас и так викликається тільки функція синусу тому її можна одразу в додати до System.out.println

2023-01-10 19:32 UTC, merged